common: &common
  adapter: postgresql
  username: root
  encoding: unicode
  pool: 5
  password:

development:
  <<: *common
  database: ankath_dev

test:
  <<: *common
  database: ankath_test

production:
  <<: *common
  database: ankath_prod
